#!/usr/bin/env bash
#Display PID and process name for processes containing the word 'bash'

for pid in /proc/*/; do
        if [ -e "$pid/status" ]; then
                process_name=$(awk -F: '/Name/{print $2}' "$pid/status" | tr -d '[:space:]')
                if [[ "$process_name" == *"bash"* ]]; then
                        pid_number=$(basename "$pid")
                        echo "$pid_number $process_name"
                fi
        fi
done
