#!/usr/bin/env bash
#Print Best school and Hii
var=1
while [ $var -le 10 ]
do
        if [ $var -eq 9 ]
        then
                echo "Best School"
                echo "Hi"
        else
                echo "Best School"
        fi
        var=$(( var + 1 )) 
done
